Конфигурация реакт проекта
softwarrior/simple-shop pull request #2
Opened 2022-09-13 21:56 UTC by softwarrior

Добрый вечер,

@Muslik большое спасибо за ревью! 

Исправил замечания которые вы указали тут: https://github.com/softwarrior/simple-shop/pull/1#pullrequestreview-1106401786

Пришлось открыть новый PR, так как старый закрылся после удаления ветки :( 
Теперь коммит работает:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/22204278/190016450-20128611-72dc-487f-b9dd-cbd2393ac736.png">

2022-09-20 12:43 UTC, Muslik requested changes
Переименуйте файлы с React компонентами в jsx. Добавьте jsx в lint staged

2022-09-20 12:43 UTC, Muslik commented on .husky/pre-commit
> +npx eslint .
Почему бы это не унести в конфигурацию lint-staged?

2022-09-20 12:43 UTC, Muslik commented on .lintstagedrc.json
> +  "*.html": "prettier --write",
```"*.{html,css,js,jsx}": ["prettier --write", "eslint --fix"],```

2022-09-20 18:29 UTC, softwarrior commented on .lintstagedrc.json
> +  "*.html": "prettier --write",
Спасибо! Исправил

2022-09-20 18:31 UTC, softwarrior commented on .husky/pre-commit
> +npx eslint .
Спасибо! Перенес

2022-09-20 18:38 UTC, softwarrior commented
Большое спасибо за ревью. Замечания исправил.

2022-09-21 09:25 UTC, Muslik approved these changes

2022-09-21 09:28 UTC, merged