Домашнее задание 2:  Собрать шапку страницы на mocks
softwarrior/simple-shop pull request #3
Opened 2022-10-26 16:52 UTC by softwarrior

Собрал шапку из компонентов.

Запись экрана что реализовано прикладываю:
https://user-images.githubusercontent.com/22204278/198087418-46207bc9-b200-450b-a660-7ccfac893948.mov

2022-10-29 15:02 UTC, Muslik requested changes
Разобрали на уроке

2022-10-31 12:18 UTC, softwarrior commented
Вторым коммитом: поправил замечания которые разобрали на уроке.

2022-11-01 00:38 UTC, Muslik requested changes
Будет видео

2022-11-03 13:18 UTC, softwarrior commented
ДЗ-2 исправления:
* Кнопка:
  - сделал невидимый border и меняю ему цвет при выделении
  - убрал стиль hidden
* Чекбокс:
  - рефакторинг( убрал Optional )
* DropdownItem:
  - Удалил
* Icon:
  - Удалил стили
* Input:
  - Удалил стиль dropdown
  - Удалил switch
  - Исправил проверку value
* Searchbar:
  - Удалил ( использую Input )
* Input:
  - Убрал children
* Смена темы:
  - меняю активную кнопку при смене темы
* Статус заказа:
  - при выборе всех статусов выставляю "Любой"
* Обработчик состояний:
  - Удалил VisibilityType
  - Убрал зависимость в обработчике состояний

2022-11-04 22:32 UTC, Muslik requested changes
Исправить derived state и еще чуток подковырять инпут

2022-11-04 22:32 UTC, Muslik commented on src/features/OrderListPage/OrderListPage.jsx
> +  useEffect(() => {
https://www.youtube.com/watch?v=tz0fDABt67g
Замечание не исправлено.

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +  iconType = iconType
Плохо и нечитаемо

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +  iconType = iconType
Сколько мне нужно времени чтобы понять что тут будет в итоге? Много

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +          disabled={inputStyle === InputStyle.disabled}
disabled должно приходить не из InputStyle.

```<Input disabled />```  и ваш инпут должен стать disabled.

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +  onButtonClick = noop,
onReset

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +  correct: "correct",
Инпут по умолчанию correct. Не нужно хранить это в стилях

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +  empty: "empty",
empty или нет вы знаете по value пришедшему. Не нужен для этого отдельный стиль

2022-11-04 22:32 UTC, Muslik commented on src/shared/components/Input/Input.jsx
> +          disabled={inputStyle === InputStyle.disabled}
Кнопка сброса должна показываться у инпута только при введенном значении.

2022-11-04 22:32 UTC, Muslik commented on src/features/OrderListPage/components/Table/Table.jsx
> +export const Table = () => <div className={styles._}></div>;
Таблицы тут не должно быть

2022-11-04 22:32 UTC, Muslik commented on src/features/OrderListPage/components/Header/Header.jsx
> +        buttonSize={ButtonSize.medium}
nitpick: И так понять что это size кнопки. Можно просто пропс size назвать

2022-11-05 04:15 UTC, softwarrior commented on src/features/OrderListPage/OrderListPage.jsx
> +  useEffect(() => {
Большое спасибо! Разобрался и исправил.

2022-11-05 04:17 UTC, softwarrior commented on src/shared/components/Input/Input.jsx
> +  iconType = iconType
Исправил. Выкинул ненужные стили и упростил.

2022-11-05 04:17 UTC, softwarrior commented on src/shared/components/Input/Input.jsx
> +          disabled={inputStyle === InputStyle.disabled}
Спасибо. Исправил.

2022-11-05 04:18 UTC, softwarrior commented on src/shared/components/Input/Input.jsx
> +  onButtonClick = noop,
Спасибо. Исправил.

2022-11-05 04:18 UTC, softwarrior commented on src/shared/components/Input/Input.jsx
> +  correct: "correct",
Спасибо. Удалил ненужные стили

2022-11-05 04:19 UTC, softwarrior commented on src/shared/components/Input/Input.jsx
> +  empty: "empty",
Спасибо. Удалил ненужные стили

2022-11-05 04:19 UTC, softwarrior commented on src/features/OrderListPage/components/Table/Table.jsx
> +export const Table = () => <div className={styles._}></div>;
Спасибо. Удалил.

2022-11-05 04:19 UTC, softwarrior commented on src/features/OrderListPage/components/Header/Header.jsx
> +        buttonSize={ButtonSize.medium}
Спасибо. Переименовал.

2022-11-05 04:20 UTC, softwarrior commented
Большое спасибо за ревью! все указанные замечания исправил.

2022-11-06 22:04 UTC, Muslik approved these changes
Есть замечания небольшие. В дальнейшем их нужно исправить.

2022-11-06 22:04 UTC, Muslik commented on src/features/OrderListPage/OrderListPage.jsx
> +    setFilterDropdownValue(filterDefaultValue);
Зачеееем )

2022-11-06 22:04 UTC, Muslik commented on src/features/OrderListPage/OrderListPage.jsx
> +  const [, setFilterDropdownValue] = useState(filterDefaultValue);
Удалить.

2022-11-06 22:04 UTC, Muslik commented on src/features/OrderListPage/OrderListPage.jsx
> +  const [filterDropdownStates, setFilterDropdownStates] = useState([]);
filterDropdownStates - очень странное название. Вообще из названия непонятно что там хранится. А хранятся там выбранные статусы. Называйте переменный более осмысленно

2022-11-06 22:04 UTC, Muslik commented on src/features/OrderListPage/OrderListPage.jsx
> +  const filterDropdownValue = useMemo(
Тоже с осмысленным названием переменную хотелось бы

2022-11-07 08:47 UTC, merged

2022-11-07 10:02 UTC, softwarrior commented on src/features/OrderListPage/OrderListPage.jsx
> +    setFilterDropdownValue(filterDefaultValue);
Спасибо. Удалил

2022-11-07 10:02 UTC, softwarrior commented on src/features/OrderListPage/OrderListPage.jsx
> +  const [, setFilterDropdownValue] = useState(filterDefaultValue);
Спасибо. Удалил

2022-11-07 10:09 UTC, softwarrior commented on src/features/OrderListPage/OrderListPage.jsx
> +  const [filterDropdownStates, setFilterDropdownStates] = useState([]);
Спасибо. Переименовал в filterSelectedStatuses

2022-11-07 10:10 UTC, softwarrior commented on src/features/OrderListPage/OrderListPage.jsx
> +  const filterDropdownValue = useMemo(
Спасибо переименовал в filterStatusText

2022-11-07 10:10 UTC, softwarrior commented
Большое спасибо за ревью! Вcе правки залил в master после мержа.