Домашнее задание 3: собрать таблицу на mocks
softwarrior/simple-shop pull request #4
Opened 2022-10-31 12:44 UTC by softwarrior

Домашнее задание 3: собрать таблицу на mocks

@Muslik заранее большое спасибо за ревью!

2022-11-01 00:45 UTC, Muslik requested changes
Будет видео

2022-11-05 04:43 UTC, softwarrior commented
ДЗ-3 исправления:

- Удалил таблицу из компонентов страницы
- Сделал общие компоненты таблицы и положил их в shared
- Создал OrdersTable внутри которой создаю таблицу из общих компонент
- Поправил выделения чекбокса
- Дропбокс с удалением управляется кнопкой
- Исправил отображение статуса заказа - иконки и текст 

Заранее большое спасибо за ревью!

2022-11-06 22:20 UTC, Muslik requested changes

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/Table.jsx
> +export const Table = ({ header, body, footer }) => (
Зачем эти пропсы. Просто напрямую передавайте:

```javascript
<Table>
  <TableHeader>
 </Table>
```

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableBody/TableBody.jsx
> +export const TableBody = ({ rows }) => {
Просто children

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableBody/TableBody.jsx
> +      <div className={styles.tableBodyCustomerList}>{rows}</div>
Лишний wrapper. Одного div-а же достаточно

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableCell/TableCell.jsx
> +        <Icon
Вот только есть проблемка. Иконка может быть в конце, может быть в начале, ее может вообще не быть.
Я бы не зашивал иконку в саму ячейку. Ячейка это просто контейнер куда вы будете передавать children-ов

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableFooter/TableFooter.jsx
> +          {firstButton}
Компонент не переиспользуемый. А если будет таблица с 5ю кнопками? Придется еще пропсов менять?
TableFooter имеет какие то свои padding-и и background. Все. А дальше принимает все children-ами

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableFooter/TableFooter.jsx
> +          {paginationButtons}
Пагинации может в принципе не быть в другой таблице

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableHeader/TableHeader.jsx
> +      {prefix}
Опять же. Достаточно сделать просто children-ов. Почему prefix нужно выделять среди других ячеек. Это просто клетка

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +      <span className={styles.tableHeaderText}>{text}</span>
Просто chilren )

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableHeaderCell/TableHeaderCell.jsx
> +export const TableHeaderCell = ({ className, text, isIcon = true }) => {
TableHeaderCell изначально предполагается для ячейки как сортировки, поэтому isActive можно положить прямо сюда. А не передавать каждый раз по новой

2022-11-06 22:20 UTC, Muslik commented on src/shared/components/Table/TableRow/TableRow.jsx
> +      {prefix}
Опять же. Просто chilren.

2022-11-06 22:20 UTC, Muslik commented on src/features/OrderListPage/components/OrdersTable/OrdersTableBody/OrdersTableBody.jsx
> +const statusIconStyle = {
Вот у вас появляются какие то статусы в константе для статусов. Так сделайте компонент Status. 
В который вы будете передавать статус и он сразу будет стилизовать все как нужно

2022-11-06 22:20 UTC, Muslik commented on src/features/OrderListPage/components/OrdersTable/OrdersTableBody/OrdersTableBody.jsx
> +              key={`${id}_1`}
Не нужен key для каждого элемента

2022-11-06 22:20 UTC, Muslik commented on src/features/OrderListPage/components/OrdersTable/OrdersTableHeader/OrdersTableHeader.jsx
> +    className: styles.tableHeaderOrderCustomer,
У вас дублируются ширины в двух местах. И при изменении ширины придется править два места.
Я бы наверное сделал OrdersTable.module.css и импортировал оттуда эти ширины.

И опять же, не стоит всегда делать вот такие константы. Почему вы не вставите это сразу в jsx.
Ведь появится хоть одно условие в дальнейшем, то вся ваша конструкция ломается. Допустим ячейку надо будет показывать в зависимости от условия. И все...

Вставляйте сразу jsx разметку.

2022-11-06 22:20 UTC, Muslik commented on src/features/OrderListPage/components/OrdersTable/OrdersTableBody/OrdersTableBody.jsx
> +  new: styles.iconPostponed,
У статусов разные цвета текстов

2022-11-07 10:23 UTC, softwarrior commented on src/shared/components/Table/TableBody/TableBody.jsx
> +export const TableBody = ({ rows }) => {
Спасибо. Исправил.

2022-11-07 10:39 UTC, softwarrior commented on src/shared/components/Table/TableBody/TableBody.jsx
> +      <div className={styles.tableBodyCustomerList}>{rows}</div>
Спасибо. Удалил.

2022-11-07 10:50 UTC, softwarrior commented on src/shared/components/Table/TableCell/TableCell.jsx
> +        <Icon
Спасибо. Удалил содержимое, оставил только children.

2022-11-07 10:52 UTC, softwarrior commented on src/shared/components/Table/TableRow/TableRow.jsx
> +      {prefix}
Спасибо. Исправил.

2022-11-07 11:15 UTC, softwarrior commented on src/shared/components/Table/Table.jsx
> +export const Table = ({ header, body, footer }) => (
Спасибо. Удалил.

2022-11-07 11:18 UTC, softwarrior commented on src/features/OrderListPage/components/OrdersTable/OrdersTableBody/OrdersTableBody.jsx
> +              key={`${id}_1`}
Спасибо. Удалил.

2022-11-07 11:30 UTC, softwarrior commented on src/shared/components/Table/TableFooter/TableFooter.jsx
> +          {firstButton}
Спасибо. Исправил.

2022-11-07 11:50 UTC, softwarrior commented on src/features/OrderListPage/components/OrdersTable/OrdersTableBody/OrdersTableBody.jsx
> +const statusIconStyle = {
Спасибо. Создал компонент Status и вынес весь код в него.

2022-11-07 12:09 UTC, softwarrior commented on src/features/OrderListPage/components/OrdersTable/OrdersTableBody/OrdersTableBody.jsx
> +  new: styles.iconPostponed,
Спасибо. Исправил.

2022-11-07 12:34 UTC, softwarrior commented on src/features/OrderListPage/components/OrdersTable/OrdersTableHeader/OrdersTableHeader.jsx
> +    className: styles.tableHeaderOrderCustomer,
Спасибо. Вынес общие константы в OrdersTable.module.css использую их в заголовке и теле.

2022-11-07 12:36 UTC, softwarrior commented
Большое спасибо за ревью. Все замечания исправил.

2022-11-10 15:50 UTC, Muslik approved these changes

2022-11-10 15:50 UTC, Muslik commented on src/features/OrderListPage/components/OrdersTable/OrdersTableHeader/OrdersTableHeader.jsx
> +            <span className={styles.tableHeaderText}>{text}</span>
Ну вот эту штуку как раз таки и можно было бы положить в TableHeaderCell.

Иначе в чем ее отличие от TableCell.
HeaderCell будет иметь другой цвет, будет выделяться при активной сортировке и будет иметь стрелочку.
Ну это на ваше усмотрение.

2022-11-10 20:29 UTC, softwarrior commented on src/features/OrderListPage/components/OrdersTable/OrdersTableHeader/OrdersTableHeader.jsx
> +            <span className={styles.tableHeaderText}>{text}</span>
Спасибо. Подумаю как лучше сделать.

2022-11-10 20:30 UTC, merged